import glob
import os
import sys

Import('env')
env = env.Clone()
env.Append(CPPPATH=['#build/fpl2cc']) # because we use/test generated headers

# there exist some .cc-based tests of fpl parts:
run_cc_tests(env);

# The "fpl_iteself" directory contains fpl source files which
# we compile and check the output of.  They generally test error
# and/or warning conditions, and thus each may or may not be
# expected to actually compile, but we do expect a particular
# result from to attempted compilation of each.
for expected in Glob('fpl_itself/*.fpl_expect'):
    basename, foo = os.path.splitext(expected.name)
    target_path = os.path.dirname(expected.get_abspath())
    source  = 'fpl_itself/' + basename + '.fpl'
    ccfile  = target_path + '/' + basename + '.cc'
    capfile = target_path + '/' + basename + '.fpl_result'
    success = target_path + '/' + basename + '.success'
    env.CaptureFplCompile(
        [ ccfile, capfile ],  [ source ],
        CAPFILE=capfile, IGNORE_EXIT=True, QUIET=True
    )
    env.CompareOut(success, [ expected, capfile ])

# ... and these are the more sophisticated tests which actually
# run the generated parsers/languages generated. Each directory
# has a separate generated language.  fpl2cc is expected to
# correctly compile that language, and the generated languages
# acre actually run and tested.
run_target_language_tests(env);

