import os

Import('env')
env = env.Clone()

env.Jemp2h('jemptest.jemp')

for scons_tprog in Glob('*.cc'):
    tprog, ext = os.path.splitext(scons_tprog.name)
    env.Program(tprog, [ tprog + '.cc' ])

    # Run the test:
    #    Command(target, source, action, [key=val, ...])
    # (note $SOURCE is the path to the tprog)
    env.Command(tprog + '.out', tprog, '$SOURCE > $TARGET')

    # compare the output of the test to the expected output;
    # .success file is/becomes up to date if output matched
    env.CompareOut(tprog + '.success', [ tprog + '.out', tprog + '.expect' ])

