Import('env')
env = env.Clone()

env.Jemp2h('jemptest.jemp')

env.Program('jemptest', [ 'jemptest.cc' ])

# Command(target, source, action, [key=val, ...])
# (note $SOURCE is the path to jemptest)
env.Command('jemptest.out', 'jemptest', '$SOURCE > $TARGET')

env.CompareOut('jemptest.success', [ 'jemptest.expect', 'jemptest.out' ])

