
Import('env')
env = env.Clone()

env.Jemp2h('scan_group_terminal.h.jemp')
env.Jemp2h('scan_inv_group_terminal.h.jemp')
env.Jemp2h('scan_inv_regex_terminal.h.jemp')
env.Jemp2h('scan_regex_terminal.h.jemp')

env.Jemp2h('fpl_x_parser.h.jemp')


env.Program('#bin/fpl2cc', [ 'fpl2cc.cc', ])

# fpl2cc is precious so that if we break fpl_parser.h
# we can still recreate it (with fpl2cc):
env.Precious('#bin/fpl2cc')

env.Fpl2h('fpl.fpl')
# env.Program('#bin/fpl', [ 'fpl.cc', ])

# test subdir:
#SConscript('test/SConstruct', 'env');


