#!/bin/sh

echo rebuilding src/util/jemplpl.cc

# recreates jemplpl.cc from jemplpl.fpl.
#bin/fpl2cc --src-path=src/grammarlib --debug-single-step src/util/jemplpl.fpl --statedump .states --out src/util/jemplpl.cc
bin/fpl2cc --src-path=src/grammarlib src/util/jemplpl.fpl --statedump .states --out src/util/jemplpl.cc

scons build/util/test/jemptest.success
